name: Deploy project
env:
  CI: false
on:
  push:
    branches:
      - main #here we choose to deploy only when a push is detected on the main branch
    paths-ignore:
      - 'README.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checkagem do lint"
      - uses: actions/checkout@v3
      - name: lint project
        run: yarn install --frozen-lockfile && yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy do serviço no S3"
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build project
        run: yarn install && yarn build
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://textify-frontend --delete
        # --delete flag will remove any file in the s3 that are not on the "thefoldertodeploy" folder
